keller_williams_marketing_box:
    resource: "@KellerWilliamsCareersBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"